name: Test Workflow

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    test-bicep:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Deploy Bicep
              id: bicep
              shell: bash
              run: cat ./infra/main.test